

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/src/components/Footer";
import Navbar from "@/src/components/Navbar";
import Header from "@/src/components/Header";
import Scrollable from "@/src/components/Scrollable";
import {ThemeChange} from "@/src/components/themeChange";
// import {ModeToggle} from "@/src/components/ModeToogle";
import {ThemeProvider} from "@/context/ThemeContext";
import LayoutWrapper from "./LayoutWrapper"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en" >

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
        >
          <LayoutWrapper>
            <ThemeProvider>

              {children}
            </ThemeProvider>
      
    </LayoutWrapper>
      </body>
    </html>
  );
}
